version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "bot.py"]
